kind: Service
apiVersion: v1
metadata:
  name: "dongbang-api"
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  labels:
    project: "dongbang"
spec:
  selector:
    app: "dongbang-api"
  ports:
    - name: "api"
      port: 80
      targetPort: 8000
  type: LoadBalancer