kind: Service
apiVersion: v1
metadata:
  name: "mongo"
  labels:
    project: "dongbang"
spec:
  selector:
    app: "mongo"
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
      nodePort: 31001
  type: NodePort
