apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    pv-name: mongo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /opt/pv/mongo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-mongo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  selector:
    matchLabels:
      pv-name: mongo