kind: Service
apiVersion: v1
metadata:
  name: "dongbnag-api"
  labels:
    project: "dongbang"
spec:
  selector:
    app: "dongbang-api"
  ports:
  - name: "http"
    protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort